site_name: Collabnix
site_url: https://dockerlabs.collabnix.com/
nav:
    - Home: index.md
    - Installation: 
      - Installing Docker Desktop for Linux: docker-desktop-for-linux.md
      - Installing Docker Desktop for Windows: docker-desktop-for-windows.md
      - Installing Docker Desktop for Mac: docker-desktop-for-mac.md
      - Installing Docker on Raspberry Pi: docker-on-raspberrypi.md
      - Installing Docker on NVIDIA Jetson: docker-on-jetson-nano.md
    - Getting Started with Docker Hub:
      - Creating Your Docker Hub Account: docker-hub.md
    - Getting Started with Docker Image:
      - Running Hello World Example: hello-world.md
      - Working with Docker Image: working-with-docker-image.md
      - Saving Images and Containers as tar files: saving-images-and-containers.md
      - Building Your First Alpine Docker Image: building-first-alpine.md 
theme: readthedocs
