[build]
  command = "python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && mkdocs build"
  publish = "site"

[context.production.environment]
  MKDOCS_ENV = "production"

